default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>

development:
  database: hippopath_development
  <<: *default

test:
  database: hippopath_test
  <<: *default

staging:
  database: hippopath_staging
  <<: *default

production:
  database: hippopath_production
  <<: *default
