development:
  server: https://hippopathchat.herokuapp.com/
  secret_token: "effd0096e91c893324cf1867da1a1a96fc3ddc2bdfefb0ccfe43129a1cedfad8"
test:
  server: https://hippopathchat.herokuapp.com/
  secret_token: "effd0096e91c893324cf1867da1a1a96fc3ddc2bdfefb0ccfe43129a1cedfad8"
production:
  server: "http://example.com/faye"
  secret_token: "effd0096e91c893324cf1867da1a1a96fc3ddc2bdfefb0ccfe43129a1cedfad8"
  signature_expiration: 3600 # one hour
