development:
  server: "http://54.191.133.42:8080/faye"
  secret_token: "secret"
  signature_expiration: 3600 # one hour
test:
  server: "http://54.191.133.42:8080/faye"
  secret_token: "secret"
production:
  server: "http://54.191.133.42:8080/faye"
  secret_token: "secret"
  signature_expiration: 3600 # one hour
