development:
  server: "http://0.0.0.0:8080/faye"
  secret_token: "secret"
test:
  server: "http://0.0.0.0:8080/faye"
  secret_token: "secret"
production:
  server: "http://0.0.0.0:8080/faye"
  secret_token: "secret"
  signature_expiration: 3600 # one hour
